Якщо ви бажаєте автоматизувати ввід данних, то відкрийте папку settings і в ній змініть файл settings.txt за наступним принципом:
PathToExcel: ПОМ ТАКСАТОРА.xlsm
ServerName: DESKTOP-O12RAHV
DatabaseName: 2122-21

Відкривши программу, вам виведеться запит, у відповіть на нього вам потрібно ввести щось одне зі списку у форматі без лапок: "file",
 "з файлу", "файл", "1", якщо хочете щоб данні зчиталися з файлу settings, який ви попередньо заповнили
 або будь-яке інше значення для заповнення вручну.



Якщо програма успішно завершить свою роботу, то виведе "Program successfully finished!" і час роботи скрипта. В іншому випадку, вона
крашнеться і запише дані про помилку у файл error.txt у вигляді:

Traceback (most recent call last):
  File "D:/Programming/Python/SQL_converter 2.0/main.py", line 57, in <module>
    sql.executemany(f"INSERT INTO {temp} VALUES(" + text, page)
pyodbc.IntegrityError: ('23000', '[23000] [Microsoft][ODBC SQL Server Driver][SQL Server]Конфликт инструкции INSERT с ограничением FOREIGN KEY "M01_KAZU". Конфликт произошел в базе данных "2122-21", таблица "dbo.NDI10100003", column \'KAZU\'. (547) (SQLExecDirectW); [23000] [Microsoft][ODBC SQL Server Driver][SQL Server]Выполнение данной инструкции было прервано. (3621)')

З цього виводу вам потрібно проаналізувати останній рядок, а саме:
Конфликт инструкции INSERT с ограничением FOREIGN KEY "M01_KAZU". Конфликт произошел в базе данных "2122-21", таблица "dbo.NDI10100003", column \'KAZU\'.
В даному випадку помилка сталася в таблиці M01 в стовпці KAZU. Причиною помилки є недопустиме значення, яке непередбачене таблицею NDI10100003.

За детальнішою інформацією звертайтеся на пошту lordoleksiy@gmail.com або в телеграм @aleksey1k. 